### Об'єкт DataFrame

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Створення DataFrame на основі словника списків
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [3]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [4]:
frame = pd.DataFrame(data)

In [5]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [7]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [8]:
# Можна задати послідовність стовпців
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [9]:
# Якщо запросити відсутній стовпець, то значення будуть NaN
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])

In [10]:
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [11]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [12]:
# Стовпець DataFrame можна вилучити як об'єкт Series
frame2['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [13]:
# Доступ до елементів loc та iloc
frame2.loc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [14]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [15]:
# Можна присвоїти скаляр цілому стовпцю
frame2['debt'] = 16.5

In [16]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [17]:
# Або діапазон
frame2['debt'] = np.arange(6.)

In [18]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [19]:
# Можна присвоїти Series, але індекси повинні відповідати DataFrame

In [20]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [21]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [22]:
frame2['debt'] = val

In [23]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [24]:
val2 = pd.Series([-1.2, -1.5, -1.7, 0.0, 0.0, 0.0], index=['two', 'four', 'five', 'one', 'three', 'zero'])

In [25]:
val2

two     -1.2
four    -1.5
five    -1.7
one      0.0
three    0.0
zero     0.0
dtype: float64

In [26]:
frame2['debt'] = val2

In [27]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [28]:
val3 = pd.Series([-1.2, -1.5, -1.7, 0.0, 0.0, 0.0], index=[0, 1, 2, 3, 4, 5])

In [29]:
frame2['debt'] = val3

In [30]:
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  -1.2
1  2001    Ohio  1.7  -1.5
2  2002    Ohio  3.6  -1.7
3  2001  Nevada  2.4   0.0
4  2002  Nevada  2.9   0.0
5  2003  Nevada  3.2   0.0

In [31]:
# Видалення стовпців
frame2['eastern'] = frame2['state'] == 'Ohio'

In [32]:
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5  -1.2     True
1  2001    Ohio  1.7  -1.5     True
2  2002    Ohio  3.6  -1.7     True
3  2001  Nevada  2.4   0.0    False
4  2002  Nevada  2.9   0.0    False
5  2003  Nevada  3.2   0.0    False

In [33]:
del frame2['eastern']

In [34]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [35]:
# DataFrame із словника словників
population = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 
              'Nevada': {2001: 2.4, 2002: 2.9}
             }

In [36]:
population

{'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}, 'Nevada': {2001: 2.4, 2002: 2.9}}

In [37]:
frame3 = pd.DataFrame(population)

In [38]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [43]:
# Об'єкти DataFrame можна транспонувати
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [44]:
# Ключі внутрішніх словників об'єднуються для утворення індексу, але якщо індекс заданий
pd.DataFrame(population, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [47]:
pdata = {'Ohio': frame3['Ohio'][:-1], 
         'Nevada': frame3['Nevada'][:2]}

In [48]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64,
 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [49]:
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [51]:
frame3.index.name = 'year'

In [52]:
frame3.columns.name = 'state'

In [53]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [54]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [55]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, -1.2],
       [2001, 'Ohio', 1.7, -1.5],
       [2002, 'Ohio', 3.6, -1.7],
       [2001, 'Nevada', 2.4, 0.0],
       [2002, 'Nevada', 2.9, 0.0],
       [2003, 'Nevada', 3.2, 0.0]], dtype=object)